version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: local-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cooperfilmes
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql